sudo: required
services:
  - docker

before_install:
  - docker build -t superteralex/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true superteralex/react-test npm test

after_success:
  - docker build -t superteralex/multi-client ./client
  - docker build -t superteralex/multi-nginx ./nginx
  - docker build -t superteralex/multi-server ./server
  - docker build -t superteralex/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push superteralex/multi-client
  - docker push superteralex/multi-nginx
  - docker push superteralex/multi-server
  - docker push superteralex/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "multi-docker"
  env: "MultiDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-223916449465"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
